### ISSUE TITLE
Package level of IndexConfig's counstructor doesn't allow to adjust performance

### ISSUE THREAD

**Issue by LerinRuss** [tzaeschke/tinspin-indexes#33]
Hi, I noticed yoy wrote that section in ReadMe.md under "performance" header.
"For kD-trees, try disabling defensive copy via IndexConfig..."
But there is no way to create IndexConfig externally as constructor has a package level of visability and there is no any factory method for creating it.
Could you check it?

**Comment by tzaeschke** [comment]
Thanks for reporting!
I'll have a look. I wouldn't expect too much performance improvement though, maybe a few percentage points. It may make a bigger difference if you are deleting a lot of entries or whole kd-trees because in that case it may avoid garbage collection.

**Comment by tzaeschke** [comment]
I added a method `IndexConfig.create()` in #34 .
