### ISSUE TITLE
IndexConfig's factory 'create' method's supposed to be static?

### ISSUE THREAD

**Issue by LerinRuss** [tzaeschke/tinspin-indexes#35]
Hi, good evening. 
I'm revisiting issue #33 and I noticed that the `create` factory method of `org.tinspin.index.IndexConfig` is no static. 
Could you please clarify if this change is intentional?

**Comment by tzaeschke** [comment]
No, this is not intentional. It it actually quite embarrassing, it just goes to show that even seemingly simple changes deserve a unit test.

I already made a new release but it may take a day or so until it is indexed in the major maven search sites.

Thanks a lot for reporting!
